# build variables
os: Visual Studio 2015
configuration: Release
platform: Any CPU
environment:
  LibraryVersion: 1.0.0
  XamarinEmail:
    secure: +SUXZSPLHwp39+Yh09d2xxVGsEgHtlSD4NT1Og5h3sg=
  XamarinPassword:
    secure: Tvdf5rZl6IOCwZbvyj9B2w==
  XamarinTestCloudApiKey:
    secure: KHTUj30UAMizCxC6Ag+XosCBX869LVbON7AWqcY0Ms+UCFY+l8PMHRj+s5i/mRmZ
  
# versioning
version: $(LibraryVersion).{build}
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: $(LibraryVersion).0
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-{branch}'

# build
branches:
  only:
    - master
before_build:
  - appveyor RegisterXamarinLicense -Email %XamarinEmail% -Password %XamarinPassword% -Product Android
  - nuget restore Genetics.sln
build: 
  project: Genetics.sln 
  verbosity: normal
on_finish:
  - appveyor UnregisterXamarinLicense -Email %XamarinEmail% -Password %XamarinPassword%

test_script:
  # build the test APK
  - cmd: msbuild GeneticsTests\GeneticsTests.csproj /p:Configuration=%configuration% /p:Platform=AnyCPU /t:PackageForAndroid
  # upload to Xamarin Test Cloud
  - cmd: packages\Xamarin.UITest.1.0.0\tools\test-cloud.exe submit GeneticsTests\bin\%configuration%\com.example.genetics.GeneticsTests.apk %XamarinTestCloudApiKey% --devices 1a154f10 --series "master" --locale "en_US" --user %XamarinEmail% --assembly-dir GeneticsUITests\bin\%configuration% --nunit-xml GeneticsUITests.Results.xml
  # upload the test results
  - ps: (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\GeneticsUITests.Results.xml))
  
# artifacts
artifacts: 
  - path: Genetics\bin\%configuration%\
    name: Genetics-$(APPVEYOR_BUILD_VERSION) 
    type: zip 
  - path: Genetics*.nupkg
  - path: Genetics*.xam
  - path: GeneticsUITests.Results.xml
