# build variables
os: Visual Studio 2015
configuration: Release
platform: Any CPU
environment:
  LibraryVersion: 1.0.0
  XamarinEmail:
    secure: +SUXZSPLHwp39+Yh09d2xxVGsEgHtlSD4NT1Og5h3sg=
  XamarinPassword:
    secure: Tvdf5rZl6IOCwZbvyj9B2w==
  XamarinTestCloudApiKey:
    secure: KHTUj30UAMizCxC6Ag+XosCBX869LVbON7AWqcY0Ms+UCFY+l8PMHRj+s5i/mRmZ
  
# versioning
version: $(LibraryVersion).{build}
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: $(LibraryVersion).0
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-{branch}'

# build
branches:
  only:
    - master
before_build:
  - appveyor RegisterXamarinLicense -Email %XamarinEmail% -Password %XamarinPassword% -Product Android
  - nuget restore Genetics.sln
build: 
  project: Genetics.sln 
  verbosity: normal
after_build:
  - ps: >-
      $nugetVersion = $env:APPVEYOR_BUILD_VERSION;
      
      Write-Host "Setting .nuspec version tag to $nugetVersion...";
      $content = (Get-Content Genetics.nuspec);
      $content = $content -replace "\$version\$", $nugetVersion;
      $content | Out-File Genetics.nuspec;
      nuget pack Genetics.nuspec;

      Write-Host "Setting component.yaml version tag to $nugetVersion...";
      $content = (Get-Content component.yaml);
      $content = $content -replace "\$version\$", $nugetVersion;
      $content | Out-File component.yaml;
      ./Tools/xamarin-component.exe package ./;
      
on_finish:
  - appveyor UnregisterXamarinLicense -Email %XamarinEmail% -Password %XamarinPassword%

test_script:
  - ps: >-
      Write-Host "Building the test APK...";
      msbuild GeneticsTests\GeneticsTests.csproj `
        /p:Configuration=$env:configuration `
        /p:Platform=AnyCPU `
        /t:PackageForAndroid
      
      Write-Host "Uploading to Xamarin Test Cloud...";
      .\packages\Xamarin.UITest.1.0.0\tools\test-cloud.exe `
        submit GeneticsTests\bin\$env:configuration\com.example.genetics.GeneticsTests.apk `
        $env:XamarinTestCloudApiKey `
        --devices 1a154f10 `
        --series "master" `
        --locale "en_US" `
        --user $env:XamarinEmail `
        --assembly-dir GeneticsUITests\bin\$env:configuration `
        --nunit-xml GeneticsUITests.Results.xml
      $testResult = $LastExitCode;
      
      Write-Host "Uploading the test results...";
      If ($testResult -ne 0 -and $testResult -ne 19)
      {
        exit $LastExitCode;
      }
      $path = (Resolve-Path .\GeneticsUITests.Results.xml); 
      $wc = (New-Object 'System.Net.WebClient'); 
      $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", $path); 
      Write-Host "Done.";
      
      exit $testResult;
  
# artifacts
artifacts: 
  - path: Genetics\bin\$(configuration)\
    name: Genetics-$(APPVEYOR_BUILD_VERSION) 
    type: zip 
  - path: Genetics*.nupkg
  - path: Genetics*.xam
